[profile.default]
src = "src"
out = "out"
libs = ["lib"]
rpc_endpoints = {sepolia = "${ETH_RPC_URL}", arb-sepolia = "${ARB_RPC_URL}"}

remappings = [
	'@openzeppelin/=lib/openzeppelin-contracts/',
	'@ccip/=lib/ccip/',
	'@chainlink/local/=lib/chainlink-local/'
]

[lint]
exclude_lints = ["mixed-case-function", "mixed-case-variable", "screaming-snake-case-immutable"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
