[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
	'@openzeppelin/=lib/openzeppelin-contracts/'
]

[lint]
exclude_lints = ["mixed-case-function", "mixed-case-variable", "screaming-snake-case-immutable"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
